services:
  rstudio:
    platform: linux/arm64/v8
    image: huazhou/ucla_biostat_203b_2023w
    ports:
      - "8787:8787"
    environment:
      PASSWORD: 203b
      ROOT: true
      DISABLE_AUTH: true
      SSH_AUTH_SOCK: /ssh-agent
    volumes:
      - "/Users/jonathanhori/203b-lecture:/home/rstudio/203b-lecture"
      - "/Users/jonathanhori/mimic:/home/rstudio/mimic"
      - "/Users/jonathanhori/203b-hw:/home/rstudio/203b-hw"
      - "~/.ssh:/home/rstudio/.ssh"
      - "/run/host-services/ssh-auth.sock:/ssh-agent"
